import Head from 'next/head'
import Navbar from '../components/Navbar'
import { useState, useEffect } from 'react'

export default function showSchools() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(true)

  useEffect(() => {
    fetch('http://localhost:3000/api/db')
      .then((res) => res.json())
      .then((data) => {
        setData(data.results)
        setLoading(false)
        console.log(data.results);
      })
    }, [])


    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div class="container pt-5">
        <div class="container text-center">
          <div class="row">
      {data.map((i) => {
        return(
              <div class="col-sm-3 pt-3">
                <div class="card px-3 pt-3">
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7jkThuSxGVqb60uk7qT9VaafeJg7Vu616gmgEAgt61A&s" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">{i.name}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">{i.city}</h6>
                    <p class="card-text">{i.address}</p>
                  </div>
                </div>
            </div>  
        );
      })}
        </div>
      </div>
    </div>
    </>
  )
}
